//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digitalis.LDTools.DOM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Digitalis.LDTools.DOM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quadrilateral is bow-tied.
        /// </summary>
        internal static string Analytics_Bowtie {
            get {
                return ResourceManager.GetString("Analytics_Bowtie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quadrilateral has colinear vertices.
        /// </summary>
        internal static string Analytics_ColinearQuad {
            get {
                return ResourceManager.GetString("Analytics_ColinearQuad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The triangle has colinear vertices.
        /// </summary>
        internal static string Analytics_ColinearTriangle {
            get {
                return ResourceManager.GetString("Analytics_ColinearTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two or more vertices have the same value.
        /// </summary>
        internal static string Analytics_Colocation {
            get {
                return ResourceManager.GetString("Analytics_Colocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both control-points have the same value.
        /// </summary>
        internal static string Analytics_Colocation_Control {
            get {
                return ResourceManager.GetString("Analytics_Colocation_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both vertices have the same value.
        /// </summary>
        internal static string Analytics_Colocation_Line {
            get {
                return ResourceManager.GetString("Analytics_Colocation_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertices and control-points have the same values.
        /// </summary>
        internal static string Analytics_Colocation_Mixed {
            get {
                return ResourceManager.GetString("Analytics_Colocation_Mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EdgeCode must be set to either a Direct Colours value or the code of another Colour Definition.
        /// </summary>
        internal static string Analytics_Colour_InvalidEdge {
            get {
                return ResourceManager.GetString("Analytics_Colour_InvalidEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour names should only contain upper- and lower-case letters, digits and the underscore, and should start with a letter.
        /// </summary>
        internal static string Analytics_Colour_InvalidName {
            get {
                return ResourceManager.GetString("Analytics_Colour_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &apos;//&apos; to comment.
        /// </summary>
        internal static string Analytics_Comment_AddSlashes {
            get {
                return ResourceManager.GetString("Analytics_Comment_AddSlashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments should start with &apos;//&apos;.
        /// </summary>
        internal static string Analytics_Comment_MissingSlashes {
            get {
                return ResourceManager.GetString("Analytics_Comment_MissingSlashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quadrilateral is concave.
        /// </summary>
        internal static string Analytics_Concave {
            get {
                return ResourceManager.GetString("Analytics_Concave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Analytics_DeleteElement {
            get {
                return ResourceManager.GetString("Analytics_DeleteElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Analytics_ElementDeleted {
            get {
                return ResourceManager.GetString("Analytics_ElementDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix bowtied quadrilateral.
        /// </summary>
        internal static string Analytics_FixedBowtie {
            get {
                return ResourceManager.GetString("Analytics_FixedBowtie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set colour.
        /// </summary>
        internal static string Analytics_FixedInvalidColour {
            get {
                return ResourceManager.GetString("Analytics_FixedInvalidColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix inverted winding.
        /// </summary>
        internal static string Analytics_FixedInvertedTarget {
            get {
                return ResourceManager.GetString("Analytics_FixedInvertedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix scaled transform.
        /// </summary>
        internal static string Analytics_FixedMatrix {
            get {
                return ResourceManager.GetString("Analytics_FixedMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Reference.
        /// </summary>
        internal static string Analytics_FixedTargetRedirect {
            get {
                return ResourceManager.GetString("Analytics_FixedTargetRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to {0}.
        /// </summary>
        internal static string Analytics_FixInvalidColour {
            get {
                return ResourceManager.GetString("Analytics_FixInvalidColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the new name.
        /// </summary>
        internal static string Analytics_FixTargetRedirect {
            get {
                return ResourceManager.GetString("Analytics_FixTargetRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix this.
        /// </summary>
        internal static string Analytics_FixThis {
            get {
                return ResourceManager.GetString("Analytics_FixThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour-value {0} cannot be found.
        /// </summary>
        internal static string Analytics_InvalidColour {
            get {
                return ResourceManager.GetString("Analytics_InvalidColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines should not use {0}.
        /// </summary>
        internal static string Analytics_InvalidColour_Line {
            get {
                return ResourceManager.GetString("Analytics_InvalidColour_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only lines should use {0}.
        /// </summary>
        internal static string Analytics_InvalidColour_Polygon {
            get {
                return ResourceManager.GetString("Analytics_InvalidColour_Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent Direct Colours should not be used.
        /// </summary>
        internal static string Analytics_InvalidDirectColour {
            get {
                return ResourceManager.GetString("Analytics_InvalidDirectColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transform is singular.
        /// </summary>
        internal static string Analytics_MatrixSingular {
            get {
                return ResourceManager.GetString("Analytics_MatrixSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author should be set.
        /// </summary>
        internal static string Analytics_PageAuthor_Missing {
            get {
                return ResourceManager.GetString("Analytics_PageAuthor_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change page&apos;s back-face culling mode.
        /// </summary>
        internal static string Analytics_PageBFC_Changed {
            get {
                return ResourceManager.GetString("Analytics_PageBFC_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove back-face culling mode.
        /// </summary>
        internal static string Analytics_PageBFC_Clear {
            get {
                return ResourceManager.GetString("Analytics_PageBFC_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primitives should use Counter-clockwise back-face culling.
        /// </summary>
        internal static string Analytics_PageBFC_Invalid {
            get {
                return ResourceManager.GetString("Analytics_PageBFC_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back-face culling mode should be set.
        /// </summary>
        internal static string Analytics_PageBFC_Missing {
            get {
                return ResourceManager.GetString("Analytics_PageBFC_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set back-face culling mode to Clockwise.
        /// </summary>
        internal static string Analytics_PageBFC_SetClockwise {
            get {
                return ResourceManager.GetString("Analytics_PageBFC_SetClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set back-face culling mode to CounterClockwise.
        /// </summary>
        internal static string Analytics_PageBFC_SetCounterClockwise {
            get {
                return ResourceManager.GetString("Analytics_PageBFC_SetCounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set back-face culling mode to Disabled.
        /// </summary>
        internal static string Analytics_PageBFC_SetUncertified {
            get {
                return ResourceManager.GetString("Analytics_PageBFC_SetUncertified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change page&apos;s Category.
        /// </summary>
        internal static string Analytics_PageCategory_Changed {
            get {
                return ResourceManager.GetString("Analytics_PageCategory_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove category.
        /// </summary>
        internal static string Analytics_PageCategory_Clear {
            get {
                return ResourceManager.GetString("Analytics_PageCategory_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove category.
        /// </summary>
        internal static string Analytics_PageCategory_Cleared {
            get {
                return ResourceManager.GetString("Analytics_PageCategory_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title specifies a part-category, but Category will override this.
        /// </summary>
        internal static string Analytics_PageCategory_Mismatch {
            get {
                return ResourceManager.GetString("Analytics_PageCategory_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category should be set.
        /// </summary>
        internal static string Analytics_PageCategory_Missing {
            get {
                return ResourceManager.GetString("Analytics_PageCategory_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove page&apos;s Category.
        /// </summary>
        internal static string Analytics_PageCategory_Remove {
            get {
                return ResourceManager.GetString("Analytics_PageCategory_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two or more keywords are the same.
        /// </summary>
        internal static string Analytics_PageKeyword_Duplicates {
            get {
                return ResourceManager.GetString("Analytics_PageKeyword_Duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more keywords also appear in the Title.
        /// </summary>
        internal static string Analytics_PageKeyword_InTitle {
            get {
                return ResourceManager.GetString("Analytics_PageKeyword_InTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove duplicate keywords.
        /// </summary>
        internal static string Analytics_PageKeyword_Removed {
            get {
                return ResourceManager.GetString("Analytics_PageKeyword_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change page&apos;s License.
        /// </summary>
        internal static string Analytics_PageLicense_Changed {
            get {
                return ResourceManager.GetString("Analytics_PageLicense_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Creative Commons license is required to submit files to the LDraw.org Parts Tracker or Official Model Repository.
        /// </summary>
        internal static string Analytics_PageLicense_Invalid {
            get {
                return ResourceManager.GetString("Analytics_PageLicense_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change page&apos;s Name.
        /// </summary>
        internal static string Analytics_PageName_Changed {
            get {
                return ResourceManager.GetString("Analytics_PageName_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set prefix-character to &apos;{0}&apos;.
        /// </summary>
        internal static string Analytics_PageName_ChangePrefix {
            get {
                return ResourceManager.GetString("Analytics_PageName_ChangePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate markers &apos;{0}&apos;.
        /// </summary>
        internal static string Analytics_PageName_DuplicateMarkers {
            get {
                return ResourceManager.GetString("Analytics_PageName_DuplicateMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should only contain the characters a-z, A-Z, 0-9, - and _.
        /// </summary>
        internal static string Analytics_PageName_InvalidChars {
            get {
                return ResourceManager.GetString("Analytics_PageName_InvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is invalid.
        /// </summary>
        internal static string Analytics_PageName_InvalidFormat {
            get {
                return ResourceManager.GetString("Analytics_PageName_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to markers &apos;{0}&apos; are in the wrong order, should be &apos;{1}&apos;.
        /// </summary>
        internal static string Analytics_PageName_InvalidMarkerSequence {
            get {
                return ResourceManager.GetString("Analytics_PageName_InvalidMarkerSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid pattern-marker &apos;{0}&apos;, should be &apos;pXX&apos;.
        /// </summary>
        internal static string Analytics_PageName_InvalidPatternMarker {
            get {
                return ResourceManager.GetString("Analytics_PageName_InvalidPatternMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid prefix-character &apos;{0}&apos;, should be s, u or x.
        /// </summary>
        internal static string Analytics_PageName_InvalidPrefix {
            get {
                return ResourceManager.GetString("Analytics_PageName_InvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid shortcut-marker &apos;{0}&apos;, should be &apos;cNN&apos; or &apos;dNN&apos;.
        /// </summary>
        internal static string Analytics_PageName_InvalidShortcutMarker {
            get {
                return ResourceManager.GetString("Analytics_PageName_InvalidShortcutMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid subpart-marker &apos;{0}&apos;, should be &apos;sNN&apos;.
        /// </summary>
        internal static string Analytics_PageName_InvalidSubpartMarker {
            get {
                return ResourceManager.GetString("Analytics_PageName_InvalidSubpartMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid suffix-character &apos;{0}&apos;, should be a letter.
        /// </summary>
        internal static string Analytics_PageName_InvalidSuffix {
            get {
                return ResourceManager.GetString("Analytics_PageName_InvalidSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing shortcut-marker, should be &apos;cNN&apos; or dNN&apos;.
        /// </summary>
        internal static string Analytics_PageName_MissingShortcutMarker {
            get {
                return ResourceManager.GetString("Analytics_PageName_MissingShortcutMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing subpart-marker, should be &apos;sNN&apos;.
        /// </summary>
        internal static string Analytics_PageName_MissingSubpartMarker {
            get {
                return ResourceManager.GetString("Analytics_PageName_MissingSubpartMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove marker &apos;{0}&apos;.
        /// </summary>
        internal static string Analytics_PageName_RemoveMarker {
            get {
                return ResourceManager.GetString("Analytics_PageName_RemoveMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove prefix-character.
        /// </summary>
        internal static string Analytics_PageName_RemovePrefix {
            get {
                return ResourceManager.GetString("Analytics_PageName_RemovePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove shortcut-marker.
        /// </summary>
        internal static string Analytics_PageName_RemoveShortcutMarker {
            get {
                return ResourceManager.GetString("Analytics_PageName_RemoveShortcutMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove suffix-character.
        /// </summary>
        internal static string Analytics_PageName_RemoveSuffix {
            get {
                return ResourceManager.GetString("Analytics_PageName_RemoveSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap marker order.
        /// </summary>
        internal static string Analytics_PageName_SwapMarkers {
            get {
                return ResourceManager.GetString("Analytics_PageName_SwapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should be no more than 21 characters in length.
        /// </summary>
        internal static string Analytics_PageName_TooLong {
            get {
                return ResourceManager.GetString("Analytics_PageName_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should not have pattern-marker &apos;{0}&apos;.
        /// </summary>
        internal static string Analytics_PageName_UnneededPatternMarker {
            get {
                return ResourceManager.GetString("Analytics_PageName_UnneededPatternMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should not have prefix-character &apos;{0}&apos;.
        /// </summary>
        internal static string Analytics_PageName_UnneededPrefix {
            get {
                return ResourceManager.GetString("Analytics_PageName_UnneededPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should not have shortcut-marker &apos;{0}&apos;.
        /// </summary>
        internal static string Analytics_PageName_UnneededShortcutMarker {
            get {
                return ResourceManager.GetString("Analytics_PageName_UnneededShortcutMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should not have subpart-marker &apos;{0}&apos;.
        /// </summary>
        internal static string Analytics_PageName_UnneededSubpartMarker {
            get {
                return ResourceManager.GetString("Analytics_PageName_UnneededSubpartMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should not have suffix-character &apos;{0}&apos;.
        /// </summary>
        internal static string Analytics_PageName_UnneededSuffix {
            get {
                return ResourceManager.GetString("Analytics_PageName_UnneededSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected format is &apos;number[suffix]&apos;.
        /// </summary>
        internal static string Analytics_PageName_Unrecognised_Alias {
            get {
                return ResourceManager.GetString("Analytics_PageName_Unrecognised_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected format is &apos;[prefix]number[suffix][pattern-code][shortcut-code]&apos;.
        /// </summary>
        internal static string Analytics_PageName_Unrecognised_Part {
            get {
                return ResourceManager.GetString("Analytics_PageName_Unrecognised_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected format is &apos;number&apos;.
        /// </summary>
        internal static string Analytics_PageName_Unrecognised_Simple {
            get {
                return ResourceManager.GetString("Analytics_PageName_Unrecognised_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected format is &apos;[prefix]number[suffix][pattern-code]subpart-code&apos;.
        /// </summary>
        internal static string Analytics_PageName_Unrecognised_Subpart {
            get {
                return ResourceManager.GetString("Analytics_PageName_Unrecognised_Subpart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change page&apos;s origin.
        /// </summary>
        internal static string Analytics_PageOrigin_Changed {
            get {
                return ResourceManager.GetString("Analytics_PageOrigin_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The origin of the page is outside its bounding-box.
        /// </summary>
        internal static string Analytics_PageOrigin_OutsideBoundingBox {
            get {
                return ResourceManager.GetString("Analytics_PageOrigin_OutsideBoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set origin to the page&apos;s bottom.
        /// </summary>
        internal static string Analytics_PageOrigin_SetCentreBottom {
            get {
                return ResourceManager.GetString("Analytics_PageOrigin_SetCentreBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set origin to the page&apos;s centre.
        /// </summary>
        internal static string Analytics_PageOrigin_SetCentreBoundingBox {
            get {
                return ResourceManager.GetString("Analytics_PageOrigin_SetCentreBoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set origin to the page&apos;s top.
        /// </summary>
        internal static string Analytics_PageOrigin_SetCentreTop {
            get {
                return ResourceManager.GetString("Analytics_PageOrigin_SetCentreTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add colour-value &apos;[{0}]&apos;.
        /// </summary>
        internal static string Analytics_PageTitle_AddColourValue {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_AddColourValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add missing tilde.
        /// </summary>
        internal static string Analytics_PageTitle_AddTilde {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_AddTilde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add missing underscore.
        /// </summary>
        internal static string Analytics_PageTitle_AddUnderscore {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_AddUnderscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title should be &apos;{0}&apos;.
        /// </summary>
        internal static string Analytics_PageTitle_AliasMismatch {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_AliasMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change page&apos;s Title.
        /// </summary>
        internal static string Analytics_PageTitle_Changed {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct spacing.
        /// </summary>
        internal static string Analytics_PageTitle_CorrectWhitespace {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_CorrectWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is invalid.
        /// </summary>
        internal static string Analytics_PageTitle_InvalidFormat {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should end with a colour-value-marker.
        /// </summary>
        internal static string Analytics_PageTitle_MissingColourValue {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_MissingColourValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to single-digit numbers should have leading spaces.
        /// </summary>
        internal static string Analytics_PageTitle_MissingSpaceBeforeNumber {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_MissingSpaceBeforeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should start with a tilde.
        /// </summary>
        internal static string Analytics_PageTitle_MissingTilde {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_MissingTilde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should start with an underscore.
        /// </summary>
        internal static string Analytics_PageTitle_MissingUnderscore {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_MissingUnderscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title should be &apos;_{0} [{1}]&apos;.
        /// </summary>
        internal static string Analytics_PageTitle_PhysicalColourMismatch {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_PhysicalColourMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove colour-value.
        /// </summary>
        internal static string Analytics_PageTitle_RemoveColourValue {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_RemoveColourValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tilde.
        /// </summary>
        internal static string Analytics_PageTitle_RemoveTilde {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_RemoveTilde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove underscore.
        /// </summary>
        internal static string Analytics_PageTitle_RemoveUnderscore {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_RemoveUnderscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title should be no more than 64 characters in length.
        /// </summary>
        internal static string Analytics_PageTitle_TooLong {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should not end with a colour-value-marker.
        /// </summary>
        internal static string Analytics_PageTitle_UnneededColourValue {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_UnneededColourValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should not start with a tilde.
        /// </summary>
        internal static string Analytics_PageTitle_UnneededTilde {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_UnneededTilde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should not start with an underscore.
        /// </summary>
        internal static string Analytics_PageTitle_UnneededUnderscore {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_UnneededUnderscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to words should be separated by single spaces.
        /// </summary>
        internal static string Analytics_PageTitle_UnneededWhitespace {
            get {
                return ResourceManager.GetString("Analytics_PageTitle_UnneededWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User should be set.
        /// </summary>
        internal static string Analytics_PageUser_Missing {
            get {
                return ResourceManager.GetString("Analytics_PageUser_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an alias for &apos;{1}&apos;.
        /// </summary>
        internal static string Analytics_TargetAlias {
            get {
                return ResourceManager.GetString("Analytics_TargetAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; will cause a model-loop.
        /// </summary>
        internal static string Analytics_TargetCircularReference {
            get {
                return ResourceManager.GetString("Analytics_TargetCircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be inverted as it is not BFC-enabled.
        /// </summary>
        internal static string Analytics_TargetInverted_Invalid {
            get {
                return ResourceManager.GetString("Analytics_TargetInverted_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models should normally not be inverted.
        /// </summary>
        internal static string Analytics_TargetInverted_Model {
            get {
                return ResourceManager.GetString("Analytics_TargetInverted_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts should normally not be inverted.
        /// </summary>
        internal static string Analytics_TargetInverted_Part {
            get {
                return ResourceManager.GetString("Analytics_TargetInverted_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should normally not be inverted.
        /// </summary>
        internal static string Analytics_TargetInverted_Primitive {
            get {
                return ResourceManager.GetString("Analytics_TargetInverted_Primitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models should normally not be mirrored.
        /// </summary>
        internal static string Analytics_TargetMirrored_Model {
            get {
                return ResourceManager.GetString("Analytics_TargetMirrored_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts should normally not be mirrored.
        /// </summary>
        internal static string Analytics_TargetMirrored_Part {
            get {
                return ResourceManager.GetString("Analytics_TargetMirrored_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should normally not be mirrored.
        /// </summary>
        internal static string Analytics_TargetMirrored_Primitive {
            get {
                return ResourceManager.GetString("Analytics_TargetMirrored_Primitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should only be mirrored in the Y direction.
        /// </summary>
        internal static string Analytics_TargetMirrored_Primitive_XZ {
            get {
                return ResourceManager.GetString("Analytics_TargetMirrored_Primitive_XZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be found.
        /// </summary>
        internal static string Analytics_TargetMissing {
            get {
                return ResourceManager.GetString("Analytics_TargetMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has been moved to &apos;{1}&apos;.
        /// </summary>
        internal static string Analytics_TargetMovedTo {
            get {
                return ResourceManager.GetString("Analytics_TargetMovedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetName should only contain the characters a-z, A-Z, 0-9, -, _ and \.
        /// </summary>
        internal static string Analytics_TargetName_InvalidChars {
            get {
                return ResourceManager.GetString("Analytics_TargetName_InvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models should normally not be scaled.
        /// </summary>
        internal static string Analytics_TargetScaled_Model {
            get {
                return ResourceManager.GetString("Analytics_TargetScaled_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts should normally not be scaled.
        /// </summary>
        internal static string Analytics_TargetScaled_Part {
            get {
                return ResourceManager.GetString("Analytics_TargetScaled_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should normally not be scaled.
        /// </summary>
        internal static string Analytics_TargetScaled_Primitive {
            get {
                return ResourceManager.GetString("Analytics_TargetScaled_Primitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should only be scaled in the Y direction.
        /// </summary>
        internal static string Analytics_TargetScaled_Primitive_XZ {
            get {
                return ResourceManager.GetString("Analytics_TargetScaled_Primitive_XZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should not be scaled in the Y direction.
        /// </summary>
        internal static string Analytics_TargetScaled_Primitive_Y {
            get {
                return ResourceManager.GetString("Analytics_TargetScaled_Primitive_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has not been released yet and contains errors.
        /// </summary>
        internal static string Analytics_TargetUnreleased_Held {
            get {
                return ResourceManager.GetString("Analytics_TargetUnreleased_Held", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has not been released yet and may have errors.
        /// </summary>
        internal static string Analytics_TargetUnreleased_Uncertified {
            get {
                return ResourceManager.GetString("Analytics_TargetUnreleased_Uncertified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has not been released yet.
        /// </summary>
        internal static string Analytics_TargetUnreleased_Unreleased {
            get {
                return ResourceManager.GetString("Analytics_TargetUnreleased_Unreleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry is missing or incomplete.
        /// </summary>
        internal static string Analytics_TexmapGeometryMissing {
            get {
                return ResourceManager.GetString("Analytics_TexmapGeometryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossmap image &apos;{0}&apos; cannot be found.
        /// </summary>
        internal static string Analytics_TexmapGlossmapMissing {
            get {
                return ResourceManager.GetString("Analytics_TexmapGlossmapMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossmap should only contain the characters a-z, A-Z, 0-9, \, -, ., and _.
        /// </summary>
        internal static string Analytics_TexmapGlossmapPathInvalidChars {
            get {
                return ResourceManager.GetString("Analytics_TexmapGlossmapPathInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossmap should be no more than 21 characters in length.
        /// </summary>
        internal static string Analytics_TexmapGlossmapPathTooLong {
            get {
                return ResourceManager.GetString("Analytics_TexmapGlossmapPathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture image &apos;{0}&apos; cannot be found.
        /// </summary>
        internal static string Analytics_TexmapTextureMissing {
            get {
                return ResourceManager.GetString("Analytics_TexmapTextureMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture should only contain the characters a-z, A-Z, 0-9, \, -, ., and _.
        /// </summary>
        internal static string Analytics_TexmapTexturePathInvalidChars {
            get {
                return ResourceManager.GetString("Analytics_TexmapTexturePathInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture should be no more than 21 characters in length.
        /// </summary>
        internal static string Analytics_TexmapTexturePathTooLong {
            get {
                return ResourceManager.GetString("Analytics_TexmapTexturePathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quadrilateral is warped by {0}°.
        /// </summary>
        internal static string Analytics_Warp {
            get {
                return ResourceManager.GetString("Analytics_Warp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BFC Flag.
        /// </summary>
        internal static string BFCFlag {
            get {
                return ResourceManager.GetString("BFCFlag", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap BFCFlagIcon {
            get {
                object obj = ResourceManager.GetObject("BFCFlagIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cacheing....
        /// </summary>
        internal static string Cacheing {
            get {
                return ResourceManager.GetString("Cacheing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified.
        /// </summary>
        internal static string Certified {
            get {
                return ResourceManager.GetString("Certified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Screen.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ClearIcon {
            get {
                object obj = ResourceManager.GetObject("ClearIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour Definition.
        /// </summary>
        internal static string ColourDefinition {
            get {
                return ResourceManager.GetString("ColourDefinition", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ColourIcon {
            get {
                object obj = ResourceManager.GetObject("ColourIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CommentIcon {
            get {
                object obj = ResourceManager.GetObject("CommentIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable back-face culling.
        /// </summary>
        internal static string DisableBackFaceCulling {
            get {
                return ResourceManager.GetString("DisableBackFaceCulling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta-command.
        /// </summary>
        internal static string ElementCategory_MetaCommand {
            get {
                return ResourceManager.GetString("ElementCategory_MetaCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable back-face culling.
        /// </summary>
        internal static string EnableBackFaceCulling {
            get {
                return ResourceManager.GetString("EnableBackFaceCulling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable back-face culling and change winding to Clockwise.
        /// </summary>
        internal static string EnableBackFaceCullingAndSetWindingModeClockwise {
            get {
                return ResourceManager.GetString("EnableBackFaceCullingAndSetWindingModeClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable back-face culling and change winding to Counter-Clockwise.
        /// </summary>
        internal static string EnableBackFaceCullingAndSetWindingModeCounterClockwise {
            get {
                return ResourceManager.GetString("EnableBackFaceCullingAndSetWindingModeCounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback Elements.
        /// </summary>
        internal static string Geometry_Fallback {
            get {
                return ResourceManager.GetString("Geometry_Fallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Elements.
        /// </summary>
        internal static string Geometry_Shared {
            get {
                return ResourceManager.GetString("Geometry_Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textured Elements.
        /// </summary>
        internal static string Geometry_Texture {
            get {
                return ResourceManager.GetString("Geometry_Texture", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GeometryIcon {
            get {
                object obj = ResourceManager.GetObject("GeometryIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GroupIcon {
            get {
                object obj = ResourceManager.GetObject("GroupIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has one or more &apos;hold&apos; votes.
        /// </summary>
        internal static string Held {
            get {
                return ResourceManager.GetString("Held", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi-res Primitive.
        /// </summary>
        internal static string HiresPrimitive {
            get {
                return ResourceManager.GetString("HiresPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap LineIcon {
            get {
                object obj = ResourceManager.GetObject("LineIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome.
        /// </summary>
        internal static string Material_Chrome {
            get {
                return ResourceManager.GetString("Material_Chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glitter.
        /// </summary>
        internal static string Material_Glitter {
            get {
                return ResourceManager.GetString("Material_Glitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matte-metallic.
        /// </summary>
        internal static string Material_MatteMetallic {
            get {
                return ResourceManager.GetString("Material_MatteMetallic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal.
        /// </summary>
        internal static string Material_Metal {
            get {
                return ResourceManager.GetString("Material_Metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pearlescent.
        /// </summary>
        internal static string Material_Pearlescent {
            get {
                return ResourceManager.GetString("Material_Pearlescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic.
        /// </summary>
        internal static string Material_Plastic {
            get {
                return ResourceManager.GetString("Material_Plastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubber.
        /// </summary>
        internal static string Material_Rubber {
            get {
                return ResourceManager.GetString("Material_Rubber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speckle.
        /// </summary>
        internal static string Material_Speckle {
            get {
                return ResourceManager.GetString("Material_Speckle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Material_Unknown {
            get {
                return ResourceManager.GetString("Material_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ModelIcon {
            get {
                object obj = ResourceManager.GetObject("ModelIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Alias.
        /// </summary>
        internal static string NewAlias {
            get {
                return ResourceManager.GetString("NewAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Hires Primitive.
        /// </summary>
        internal static string NewHiresPrimitive {
            get {
                return ResourceManager.GetString("NewHiresPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Model.
        /// </summary>
        internal static string NewModel {
            get {
                return ResourceManager.GetString("NewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Part.
        /// </summary>
        internal static string NewPart {
            get {
                return ResourceManager.GetString("NewPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Physical-Colour Shortcut.
        /// </summary>
        internal static string NewPhysical_Colour {
            get {
                return ResourceManager.GetString("NewPhysical_Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Primitive.
        /// </summary>
        internal static string NewPrimitive {
            get {
                return ResourceManager.GetString("NewPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Shortcut.
        /// </summary>
        internal static string NewShortcut {
            get {
                return ResourceManager.GetString("NewShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Shortcut Alias.
        /// </summary>
        internal static string NewShortcutAlias {
            get {
                return ResourceManager.GetString("NewShortcutAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Subpart.
        /// </summary>
        internal static string NewSubpart {
            get {
                return ResourceManager.GetString("NewSubpart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional-Line.
        /// </summary>
        internal static string OptionalLine {
            get {
                return ResourceManager.GetString("OptionalLine", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap OptionalLineIcon {
            get {
                object obj = ResourceManager.GetObject("OptionalLineIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        internal static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part (Alias).
        /// </summary>
        internal static string Part_Alias {
            get {
                return ResourceManager.GetString("Part_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part (Physical-Colour).
        /// </summary>
        internal static string Part_Physical_Colour {
            get {
                return ResourceManager.GetString("Part_Physical_Colour", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PartAliasIcon {
            get {
                object obj = ResourceManager.GetObject("PartAliasIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PartIcon {
            get {
                object obj = ResourceManager.GetObject("PartIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PartPhysicalColourIcon {
            get {
                object obj = ResourceManager.GetObject("PartPhysicalColourIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Render.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PauseIcon {
            get {
                object obj = ResourceManager.GetObject("PauseIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primitive.
        /// </summary>
        internal static string Primitive {
            get {
                return ResourceManager.GetString("Primitive", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PrimitiveIcon {
            get {
                object obj = ResourceManager.GetObject("PrimitiveIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private file.
        /// </summary>
        internal static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrilateral.
        /// </summary>
        internal static string Quadrilateral {
            get {
                return ResourceManager.GetString("Quadrilateral", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap QuadrilateralIcon {
            get {
                object obj = ResourceManager.GetObject("QuadrilateralIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for release.
        /// </summary>
        internal static string ReadyForRelease {
            get {
                return ResourceManager.GetString("ReadyForRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released.
        /// </summary>
        internal static string Released {
            get {
                return ResourceManager.GetString("Released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released, but being reworked.
        /// </summary>
        internal static string Rework {
            get {
                return ResourceManager.GetString("Rework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Screen.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SaveIcon {
            get {
                object obj = ResourceManager.GetObject("SaveIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change winding to Clockwise.
        /// </summary>
        internal static string SetWindingModeClockwise {
            get {
                return ResourceManager.GetString("SetWindingModeClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change winding to Counter-Clockwise.
        /// </summary>
        internal static string SetWindingModeCounterClockwise {
            get {
                return ResourceManager.GetString("SetWindingModeCounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        internal static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut (Alias).
        /// </summary>
        internal static string Shortcut_Alias {
            get {
                return ResourceManager.GetString("Shortcut_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut (Physical-Colour).
        /// </summary>
        internal static string Shortcut_Physical_Colour {
            get {
                return ResourceManager.GetString("Shortcut_Physical_Colour", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ShortcutAliasIcon {
            get {
                object obj = ResourceManager.GetObject("ShortcutAliasIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShortcutIcon {
            get {
                object obj = ResourceManager.GetObject("ShortcutIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShortcutPhysicalColourIcon {
            get {
                object obj = ResourceManager.GetObject("ShortcutPhysicalColourIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the viewpoint rotation to (x:{0}° y:{1}° z:{2}°).
        /// </summary>
        internal static string Step_Absolute {
            get {
                return ResourceManager.GetString("Step_Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate the viewpoint by (x:{0}° y:{1}° z:{2}°) relative to the previous setting.
        /// </summary>
        internal static string Step_Additive {
            get {
                return ResourceManager.GetString("Step_Additive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate the viewpoint by (x:{0}° y:{1}° z:{2}°) relative to its default setting.
        /// </summary>
        internal static string Step_Relative {
            get {
                return ResourceManager.GetString("Step_Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore the viewpoint to its default setting.
        /// </summary>
        internal static string Step_Reset {
            get {
                return ResourceManager.GetString("Step_Reset", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap StepIcon {
            get {
                object obj = ResourceManager.GetObject("StepIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SubassemblyIcon {
            get {
                object obj = ResourceManager.GetObject("SubassemblyIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subpart.
        /// </summary>
        internal static string Subpart {
            get {
                return ResourceManager.GetString("Subpart", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SubpartIcon {
            get {
                object obj = ResourceManager.GetObject("SubpartIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture.
        /// </summary>
        internal static string Texmap {
            get {
                return ResourceManager.GetString("Texmap", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap TexmapIcon {
            get {
                object obj = ResourceManager.GetObject("TexmapIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle.
        /// </summary>
        internal static string Triangle {
            get {
                return ResourceManager.GetString("Triangle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap TriangleIcon {
            get {
                object obj = ResourceManager.GetObject("TriangleIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet certified.
        /// </summary>
        internal static string Uncertified {
            get {
                return ResourceManager.GetString("Uncertified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unknown&gt;.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreleased.
        /// </summary>
        internal static string Unreleased {
            get {
                return ResourceManager.GetString("Unreleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying....
        /// </summary>
        internal static string Verifying {
            get {
                return ResourceManager.GetString("Verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Message.
        /// </summary>
        internal static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap WriteIcon {
            get {
                object obj = ResourceManager.GetObject("WriteIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
